#部署服务器地址
#node1: 10.37.129.3
node1: 127.0.0.1
spring:
  application:
    name: FTBook-EurekaServer
---
spring:
  profiles:
    - peer1
server:
  port: 8100
eureka:
  instance:
    prefer-ip-address: true
    server:
      enable-self-preservation: false
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${node1}:8200/eureka/
---
spring:
  profiles:
    - peer2
server:
  port: 8200
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${node1}:8100/eureka/

