eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://centerosnode2:8200/eureka/
  instance:
    hostname: centerosnode1
  server:
    enable-self-preservation: false
server:
  port: 8100
spring:
  application:
    name: FTBook-EurekaServer
