spring:
  application:
    name: FTBook-EurekaServer
---
spring:
  profiles:
    - peer1
server:
  port: 8100
eureka:
  instance:
    hostname: peer1
    server:
      enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://peer2:8200/eureka/
---
spring:
  profiles:
    - peer2
server:
  port: 8200
eureka:
  instance:
    hostname: peer2
  server:
    enable-self-preservation: false
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://peer1:8100/eureka/

