spring:
  application:
    name: FTBook-UserCenterService
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8100/eureka/,http://peer2:8200/eureka/
server:
  port: 8102
logging:
  level:
    #com.netflix: DEBUG
    com:
      mytime: DEBUG
    org:
      springframework:
        security: DEBUG
security:
  oauth2:
    client:
      client-id: pcweb
      client-secret: 123456
      user-authorization-uri: http://localhost:8104/auth/oauth/authorize
      access-token-uri: http://localhost:8104/auth/oauth/token
      registered-redirect-uri:
    resource:
      jwt:
        key-uri: http://localhost:8104/auth/oauth/token_key
