#部署服务器地址
#node1: 10.37.129.3
node1: 127.0.0.1
server:
  port: 8101  # 端口号
spring:
  application:
    name: apizuul   # 网关服务名称
eureka:
  client:
    service-url:
      defaultZone: http://${node1}:8100/eureka,http://${node1}:8200/eureka
  #instance:
  #  prefer-ip-address: true   # 返回ip地址而不是hostname

#认证服务器地址
oauth-server: http://localhost:8104/authserver
security:
  oauth2:
    resource:
      id: platform
      #      资源服务器三种验证令牌方法
      #       一、在ResourceServerConfig中本地配置
      #      二、从认证服务器获取用户信息 解析出token
      #      user-info-uri: ${oauth-server}/oauth2_token/current
      #      prefer-token-info: false
      #       三、远程获取公钥 解析token
      jwt:
        key-uri: ${oauth-server}/oauth/token_key

management:
  endpoints:
    web:
      exposure:
        #include: routes,filters
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

zuul:
  routes:
    platform:
      path: /platform/**
      sensitiveHeaders:
      serviceId: platform
      stripPrefix: false
    oauth-server:
      path: /authserver/**
      sensitiveHeaders:
      serviceId: authserver
      stripPrefix: false
    #  忽略路由
#  ignored-patterns:  /**/v2/api-docs
swagger:
  title: SpringCloud项目开发文档
  description: sso测试
  version: 1.0