spring:
  application:
    name: platform
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8100/eureka/,http://peer2:8200/eureka/
  #instance:
   # prefer-ip-address: true
server:
  port: 8199
  servlet:
    context-path: /platform
logging:
  path: ./logs
  level:
    root: info
  #config: classpath:logback-spring.xml
    com.netflix: DEBUG
    com:
      mytime: DEBUG
    org:
      springframework:
        security: DEBUG
oauth-server: http://localhost:8104/authserver
security:
  oauth2:
    resource:
      id: platform
      #      资源服务器三种验证令牌方法
      #       一、在ResourceServerConfig中本地配置
      #      二、从认证服务器获取用户信息 解析出token
      #      user-info-uri: ${oauth-server}/oauth2_token/current
      #      prefer-token-info: false
      #       三、远程获取公钥 解析token
      jwt:
        key-uri: ${oauth-server}/oauth/token_key
#开启feign支持断路器保护
feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds: 70000
# ribbon配置
#ribbon:
#  eureka:
#    enabled: true
#    MaxConnectionsPerHost: 300
#  MaxTotalConnections: 1000
#  ConnectTimeout: 60000
#  ReadTimeout: 60000
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 1