spring:
  application:
    name: FTBook-Platform
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8100/eureka/,http://peer2:8200/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8199
  servlet:
    context-path: /platform
logging:
  path: ./logs
  level:
    root: info
  #config: classpath:logback-spring.xml
    com.netflix: DEBUG
    com:
      mytime: DEBUG
    org:
      springframework:
        security: DEBUG
security:
  oauth2:
    client:
      client-id: ftbook
      client-secret: 123456
      user-authorization-uri: http://localhost:8104/auth/oauth/authorize
      access-token-uri: http://localhost:8104/auth/oauth/token
      registered-redirect-uri:
      clientAuthenticationScheme: form
