#部署服务器地址
node1: 10.37.129.3
spring:
  application:
    name: authserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=UTC&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: oauth
    password: 123456
  thymeleaf:
    #prefix: classpath:/views/
    suffix: .html
    mode: HTML
    cache: false
    mvc:
      throw-exception-if-no-handler-found: true
logging:
  level:
    #com.netflix: DEBUG
    #org.springframework: DEBUG
    #com.thoughtmechanix: DEBUG
    com:
      mytime: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
server:
  servlet:
    context-path: /authserver
  port: 8104
eureka:
  client:
    service-url:
      defaultZone: http://${node1}:8100/eureka,http://${node1}:8200/eureka
  #instance:
   # prefer-ip-address: true

